---
title: "Visualisation of Australian Influenza Cases"
author: "Neil Saunders"
date: "compiled `r Sys.time()`"
output:
  html_document:
    keep_md: yes
    number_sections: yes
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)

# read data
flu <- read_delim("../../data/flu.txt", " ", escape_double = FALSE, trim_ws = TRUE)
flu[6, "TOTALS"] <- flu[6, "SEPTEMBER"]
flu[6, "SEPTEMBER"] <- NA
```

# Introduction
More [years as coloured bars](http://www.abc.net.au/news/2017-08-21/flu-influenza-why-2017-has-been-a-particularly-bad-year/8826512). Can we do better?

For future reference, data is updated by the [Immunisation Coalition](http://www.immunisationcoalition.org.au/news-media/2017-statistics/).

# Visualisations
This is clean, but lacks in quick comparison across all years.

```{r plot-cases-1}
flu %>%
  select(-TOTALS) %>%
  gather(month, cases, -YEAR) %>%
  mutate(month = factor(month, levels = toupper(month.name))) %>%
  ggplot(aes(month, cases)) +
    geom_line(group = 1, colour = "#008acc") +
    facet_wrap(~YEAR, ncol = 3) +
    scale_x_discrete(labels = 1:12) +
    theme_bw() +
    labs(title = "Annual Australian Influenza Statistics",
         subtitle = "Source: Immunisation Coalition")
```

This allows "vertical comparison" by month, but is a little "noisy on the eyes".

```{r plot-cases-2}
flu %>%
  select(-TOTALS) %>%
  gather(month, cases, -YEAR) %>%
  mutate(month = factor(month, levels = toupper(month.name))) %>%
  ggplot(aes(month, cases)) +
    geom_col(fill = "#008acc") +
    facet_grid(YEAR ~ .) +
    scale_x_discrete(labels = 1:12) +
    theme_bw() +
    labs(title = "Annual Australian Influenza Statistics",
         subtitle = "Source: Immunisation Coalition")
```

How about conversion to date and plot a continuous timeline?

```{r plot-cases-3}
flu %>% 
  select(-TOTALS) %>% 
  gather(month, cases, -YEAR) %>% 
  mutate(Date = paste(YEAR, month, "1", sep = "-")) %>% 
  mutate(Date = as.Date(Date, "%Y-%B-%d")) %>% 
  ggplot(aes(Date, cases)) + 
    geom_line(group = 1, color = "#008acc") + 
    theme_bw() + 
    scale_x_date(date_breaks = "6 months") + 
    labs(title = "Annual Australian Influenza Statistics",
         subtitle = "Source: Immunisation Coalition") +
    theme(axis.text.x = element_text(size = 6))
```
